config/routes.rb
Rainforest::Application.routes.draw do

  get "reviews/show"

  get "reviews/new"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "users/new"

  get "users/create"

  resources :products do
    resources :reviews, :except => [:index]
  end
  
  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  root :to => "products#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, :through => :reviews
  attr_accessible :description, :name, :price_in_cents

  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end 

end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :comment, :product_id, :user_id

  belongs_to :user
  belongs_to :product

  validates_presence_of :comment
  validates_uniqueness_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  validates_presence_of :password, :on => :create
  validates_presence_of :name
  validates_presence_of :email
  validates_uniqueness_of :email
  
  has_many :reviews
  has_many :products, :through => :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :ensure_logged_in, :only => [:show, :new]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end 
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end 
  
  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end 
    end   
  end
  
  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # The load product method retreives the appropriate product so a new review can be associated to it.
  before_filter :load_product
  before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]

  def show
    @review = Review.find(params[:id])
  end

  def create
    # @review = @product.reviews.build(
    #   comment: params[:review][:comment],
    #   user_id: current_user.id
    #   )
      # Check out this article on [.build](http://stackoverflow.com/questions/783584/ruby-on-rails-how-do-i-use-the-active-record-build-method-in-a-belongs-to-rel)
      # You could use a longer alternate syntax if it makes more sense to you
      # 
      @review = Review.new(
        :comment    => params[:review][:comment], 
        :product_id => @product.id, 
        :user_id    => current_user.id
      )

    if @product.users.include? current_user
      redirect_to @product, notice: 'Cannot review a product more then once.' 
    else
      if @review.save
          redirect_to products_path, notice: 'Review created successfully'
        else
          render :action => :show
      end
    end
  end

  def edit
    @review = Review.find(params[:id])
  end 

  def update
    @review = Review.find(params[:id])

      if @review.update_attributes(params[:review])
        redirect_to @product, notice: 'Review was successfully updated.'
      else
        render action: "edit"
      end   
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to @product
  end

  private

  def load_product
    @product = Product.find(params[:product_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # def new
  # end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
      if @user.save
        redirect_to products_url, :notice => "Signed up!"
      else
        render "new"
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
<p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p>

<%= yield %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products total:  <%= @products.length %></h1>
<%= link_to "New Product", new_product_path %>

<% @products.each do |product| %>
  <p><%= product[:name] %>, <%= truncate(product[:description], length: 50) %></p>
  <p>$<%= product.formatted_price %>
  <p><%= link_to "Show Product", "products/#{product.id}" %></p>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= link_to "Back to Products", products_path %>

<p><%= @product[:name] %>, <%= @product[:description] %></p>
<p>$<%= @product.formatted_price %>
<p><%= link_to "Back to Products", products_path %> | <%= link_to "Edit", edit_product_path(@product) %> | <%= link_to "Delete", @product, :confirm => "Are you sure you want to delete this product?", :method => :delete %></p>

<% if current_user %>

  <%= render 'reviews/form2' %>

<% end %>

<% if current_user %>

  <h4>New Review</h4>

  <%= render 'reviews/form' %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
<% end %>

app/views/reviews/_form.html.erb
<%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/reviews/_form2.html.erb
<h3>Reviews</h3>

<h4>Reviews for <%= @product.name %></h4>

  <% @product.reviews.each do |review| %>
    <p>
      <%= review.comment %>
      <br>
      <% if review.user != nil %>
        <em> by <%= review.user.email %></em>
        Added on: <%= review.created_at %>
        <%= link_to "Edit", edit_product_review_path(@product, review) %> | <%= link_to "Delete", [@product, review], :confirm => "Are you sure you want to delete this review?", :method => :delete %>
      <% end %>
    </p>
  <% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>